version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        EXPRESS_SERVER_HOST_PORT: express-server:3001
      tags:
        - juliusdelapena1984/inc-attendance-monitor-web-ngrok:v0.001
        - juliusdelapena1984/inc-attendance-monitor-web-ngrok:latest
    ports:
      - "80:80" # Expose web on host port 80
    depends_on:
      - express-server # web depends on Express server for API calls during development
    networks:
      - my_app_network # Ensure they are on the same network
    restart: always
#    environment:
#      - EXPRESS_SERVER_HOST_PORT=express-server:3001

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
      tags:
        - juliusdelapena1984/inc-attendance-monitor-express-server-ngrok:v0.001
        - juliusdelapena1984/inc-attendance-monitor-express-server-ngrok:latest
    ports:
      - "3001:3001" # Express server port
    depends_on:
      - data-service # Express server depends on Python api
    networks:
      - my_app_network # Ensure they are on the same network
    restart: always
    environment:
      # override or set the backend target here
      - API_DATA_SERVICE_URL=http://data-service:5000

  data-service:
    build:
      context: ./api
      dockerfile: Dockerfile
      tags:
        - juliusdelapena1984/inc-attendance-monitor-data-service-ngrok:v0.001
        - juliusdelapena1984/inc-attendance-monitor-data-service-ngrok:latest
    ports:
      - "5000:5000" # Python api port
    networks:
      - my_app_network # Ensure they are on the same network
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    environment:
      NGROK_AUTHTOKEN: "30gGsvP0CveANEYtIXwqvh2H0AK_2j3FeWM4gVr118xHDixNX" # Replace with your actual ngrok auth token
      NGROK_PORT: "web:80" # Tunnel the React web's port
      NGROK_BINDTLS: "true" # Optional: Only open HTTPS tunnel
    ports:
      - "4040:4040" # Expose ngrok's web interface for inspection (optional)
    networks:
      - my_app_network # Ensure they are on the same network
    depends_on:
      - web # ngrok depends on the web being up
    command: "http web:80" # Command to start the ngrok tunnel
    restart: always

networks:
  my_app_network: