-- Drop existing tables (in reverse dependency order)
DROP TABLE IF EXISTS LOCALES;
-- Table 6: LOCALES
CREATE TABLE LOCALES (
    LOCALE_ID INTEGER,
    NAME VARCHAR(100),
    DISTRICT VARCHAR(100),
    ADDRESS VARCHAR(255)
);

DROP TABLE IF EXISTS MEMBERS;
-- Table 3: MEMBERS
CREATE TABLE MEMBERS (
    MEMBER_ID INTEGER PRIMARY KEY,
    LOCALE_ID INTEGER,
    FULL_NAME VARCHAR(255),
    AREA_GROUP VARCHAR(255),
    CFO VARCHAR(255),
    OFFICE VARCHAR(255),
    FOREIGN KEY (LOCALE_ID) REFERENCES LOCALES(LOCALE_ID)
);

DROP TABLE IF EXISTS VENUES;
-- Table 4: VENUES
CREATE TABLE VENUES (
    VENUE_ID INTEGER PRIMARY KEY,
    LOCALE_ID INTEGER,
    CODE VARCHAR(100),
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    FOREIGN KEY (LOCALE_ID) REFERENCES LOCALES(LOCALE_ID)
);

DROP TABLE IF EXISTS EVANGELICAL_WORKER;
-- Table 5: EVANGELICAL_WORKER
CREATE TABLE EVANGELICAL_WORKER (
    ASGD_NO VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(255),
    PHOTO TEXT
);


DROP TABLE IF EXISTS BIBLE_MISSION;
-- Table 1: BIBLE_MISSION
CREATE TABLE BIBLE_MISSION (
    EVENT_ID INTEGER PRIMARY KEY,
    LOCALE_ID INTEGER,
    SCHEDULE DATETIME,
    VENUE_ID INTEGER,
    WORKER_NAME VARCHAR(255),
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_TS DATETIME,
    FOREIGN KEY (LOCALE_ID) REFERENCES LOCALES(LOCALE_ID),
    FOREIGN KEY (VENUE_ID) REFERENCES VENUES(VENUE_ID)
);

DROP TABLE IF EXISTS MEMBER_GUEST_ATTENDANCE;
-- Table 2: MEMBER_GUEST_ATTENDANCE
CREATE TABLE MEMBER_GUEST_ATTENDANCE (
    ID INTEGER PRIMARY KEY,
    EVENT_ID INTEGER NOT NULL,
    MEMBER_ID INTEGER,
    GUESTS VARCHAR(255),
    FOREIGN KEY (EVENT_ID) REFERENCES BIBLE_MISSION(EVENT_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);





